import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";

type InviteRole = "socio_admin_master" | "socio_admin" | "comercial" | "financeiro" | "leitura" | "associado" | "representada_admin" | "representada_leitura";
interface InviteRequest { email: string; fullName: string; roleCode: InviteRole; partnerPercentage?: number; scopeType?: "manufacturer" | "customer" | "partner"; scopeId?: string; organizationId: string; }
const allowedRoles = new Set<InviteRole>(["socio_admin_master", "socio_admin", "comercial", "financeiro", "leitura", "associado", "representada_admin", "representada_leitura"]);
function responseHeaders(req: Request): HeadersInit { const origin = req.headers.get("origin") ?? ""; const configuredOrigins = (Deno.env.get("APP_ALLOWED_ORIGINS") ?? "").split(",").map((v) => v.trim()).filter(Boolean); const headers: HeadersInit = { "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS", "Vary": "Origin", "Content-Type": "application/json; charset=utf-8" }; if (origin && configuredOrigins.includes(origin)) headers["Access-Control-Allow-Origin"] = origin; return headers; }
function json(req: Request, body: Record<string, unknown>, status: number): Response { return new Response(JSON.stringify(body), { status, headers: responseHeaders(req) }); }
function base64Url(bytes: Uint8Array): string { let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
async function secureInvitationToken(): Promise<{ raw: string; hash: string }> { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); const raw = base64Url(bytes); const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(raw)); return { raw, hash: base64Url(new Uint8Array(digest)) }; }
serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: responseHeaders(req) });
  if (req.method !== "POST") return json(req, { error: "Método não permitido." }, 405);
  const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? ""; const anonKey = Deno.env.get("SUPABASE_ANON_KEY") ?? ""; const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""; const authHeader = req.headers.get("Authorization");
  if (!supabaseUrl || !anonKey || !serviceRoleKey) return json(req, { error: "Configuração segura da função ausente no servidor." }, 500); if (!authHeader?.startsWith("Bearer ")) return json(req, { error: "Sessão não informada." }, 401);
  try {
    const callerClient = createClient(supabaseUrl, anonKey, { global: { headers: { Authorization: authHeader } }, auth: { persistSession: false, autoRefreshToken: false } }); const { data: callerData, error: callerError } = await callerClient.auth.getUser(); if (callerError || !callerData.user) return json(req, { error: "Sessão inválida ou expirada." }, 401);
    const body = await req.json() as InviteRequest; const email = body.email?.trim().toLowerCase(); const fullName = body.fullName?.trim();
    if (!email || !fullName || !body.organizationId || !body.roleCode) return json(req, { error: "email, fullName, roleCode e organizationId são obrigatórios." }, 400); if (!allowedRoles.has(body.roleCode)) return json(req, { error: "Perfil não permitido." }, 400); if (["representada_admin", "representada_leitura"].includes(body.roleCode) && body.scopeType !== "manufacturer") return json(req, { error: "Representada exige escopo manufacturer." }, 400); if (body.roleCode === "associado" && body.scopeType !== "customer") return json(req, { error: "Associado exige escopo customer." }, 400); if ((body.scopeType && !body.scopeId) || (!body.scopeType && body.scopeId)) return json(req, { error: "scopeType e scopeId devem ser informados juntos." }, 400);
    const admin = createClient(supabaseUrl, serviceRoleKey, { auth: { persistSession: false, autoRefreshToken: false } }); const { data: membership, error: membershipError } = await admin.from("memberships").select("role_code, is_active").eq("organization_id", body.organizationId).eq("user_id", callerData.user.id).maybeSingle(); if (membershipError || membership?.role_code !== "socio_admin_master" || !membership.is_active) return json(req, { error: "Apenas socio_admin_master ativo pode convidar usuários." }, 403);
    const { data: existing } = await admin.from("member_invitations").select("id, status, expires_at").eq("organization_id", body.organizationId).eq("email", email).eq("status", "pending").gt("expires_at", new Date().toISOString()).maybeSingle(); if (existing) return json(req, { error: "Já existe um convite pendente para este e-mail.", invitationId: existing.id }, 409);
    const token = await secureInvitationToken(); const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(); const { data: invitation, error: insertError } = await admin.from("member_invitations").insert({ organization_id: body.organizationId, email, full_name: fullName, role_code: body.roleCode, partner_percentage: body.partnerPercentage ?? 0, scope_type: body.scopeType ?? null, scope_id: body.scopeId ?? null, status: "pending", invited_by: callerData.user.id, token: token.hash, expires_at: expiresAt }).select("id, email, full_name, role_code, status, expires_at").single(); if (insertError || !invitation) return json(req, { error: "Não foi possível registrar o convite." }, 500);
    const { data: invited, error: authError } = await admin.auth.admin.inviteUserByEmail(email, { data: { full_name: fullName, invitation_id: invitation.id, organization_id: body.organizationId, role_code: body.roleCode } }); if (authError || !invited.user) { await admin.from("member_invitations").update({ status: "revoked", updated_at: new Date().toISOString() }).eq("id", invitation.id).eq("status", "pending"); return json(req, { error: "O convite Auth não foi enviado; o registro pendente foi revogado." }, 502); }
    const { error: auditError } = await admin.from("audit_events").insert({ organization_id: body.organizationId, user_id: callerData.user.id, entity_name: "member_invitations", entity_id: invitation.id, action: "INVITE_MEMBER", changes: { email, role_code: body.roleCode, scope_type: body.scopeType ?? null, scope_id: body.scopeId ?? null } }); if (auditError) return json(req, { error: "Convite enviado, mas a auditoria falhou; revisar antes de novo convite.", invitationId: invitation.id }, 500);
    return json(req, { success: true, invitation: { ...invitation, authUserId: invited.user.id } }, 201);
  } catch (error) { return json(req, { error: error instanceof Error ? error.message : "Erro interno ao processar convite." }, 500); }
});